[package]
edition = "2021"
name = "duco2mqtt"
version = "0.1.4"
default-run = "duco2mqtt"

[dependencies]
bytes = "1.5.0"
env_logger = "0.10.2"
tokio = { version = "1.35.1", features = ["macros", "net", "io-util", "rt"] }
log = "0.4.20"
clap = { version = "4.4.18", features = ["derive", "env"] }
rumqttc = "0.23.0"
tokio-modbus = { version = "0.10.0", default-features = false, features = [
    "tcp",
] }
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
strum = { version = "0.25.0", features = ["derive"] }
async-trait = "0.1.77"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
